config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :places
  get 'static_pages/rules'

end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user

  geocoded_by :address
  after_validation :geocode

  validates :name, length: {minimum: 3}
  validates :address, length: {minimum: 5}
  validates :description, length: {minimum: 9}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to places_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
  end

  def edit
    @place = Place.find(params[:id])
    
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @place.update_attributes(place_params)
    redirect_to places_path
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
    @place.destroy
    redirect_to places_path

  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address, :restroom, :water, :parking)
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def rules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basketball Spots</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

          <%= link_to 'Hoop Spots', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to new_place_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              Add new b-ball spot
            <% end %>
          </li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Basketball Etiquette', static_pages_rules_path %></li>

          <% if user_signed_in? %>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="frosty text-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Edit Basketball Spot</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <div class="buttons">
      <div class="radio_buttons col-xs-4">
        <%= f.input :restroom, as: :radio_buttons, collection: %w[Yes No Not\ Sure], label: "Are there restrooms nearby?"%>
      </div>
      <div class="radio_buttons col-xs-4">
        <%= f.input :parking, as: :radio_buttons, collection: %w[Yes No Not\ Sure], label: "Is there plenty of parking?"%>
      </div>
      <div class="radio_buttons col-xs-4">
        <%= f.input :water, as: :radio_buttons, collection: %w[Yes No Not\ Sure], label: "Is there water nearby?"%>

      </div>
    </div>

    <div><%= f.submit 'Update Changes', class: 'btn btn-primary' %></div>

    <br>

  <% end %>
</div>

app/views/places/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>


    <title>Hoop Spots</title>



  </head>
  <body>

    <br><br>
    <div class="text-center col-xs-12">
      <h1 class="text-center"><i class="glyphicon glyphicon-arrow-down"></i> Places to Hoop <i class="glyphicon glyphicon-arrow-down"></i></h1>
    </div>

    <div class="text-center">
      <small>**This site is still under construction. Features such as searching closest location by zipcode will be added in the near future.**</small>
    </div>

      <br><br><br><br><br>
      <% @places.each do |place| %>
        <div class="frosty col-xs-10 col-xs-offset-1 ">
          <br>
          <h1><%= place.name %></h1>
          <br>

          <br>
          <strong>Address:</strong> <i><%= place.address %></i>
          <br>
          <p><%= link_to 'click here for map location', place_path(place) %></p>
          <br><br>
          <strong>Description:</strong> <%= place.description %>
          <br>
          <br>
          <strong>Additional info:</strong>
          <br>
          Restroom: <%= place.restroom %>
          <br>
          Parking: <%= place.parking %>
          <br>
          Water: <%= place.water %>
          <br>
          <br>

          <% if place.user.present? %>
            <small><strong>User: </strong> <%= place.user.email %></small>
          <% end %>
          <hr>
        </div>
      <% end %>





  </body>
</html>

app/views/places/new.html.erb
<div class="frosty text-box col-xs-10 col-xs-offset-1">
  <h1>Enter a new Basketball Spot</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br>
    <div class="buttons">
      <div class="radio_buttons col-xs-4">
        <%= f.input :restroom, as: :radio_buttons, collection: %w[Yes No Not\ Sure], label: "Are there restrooms nearby?"%>
      </div>
      <div class="radio_buttons col-xs-4">
        <%= f.input :parking, as: :radio_buttons, collection: %w[Yes No Not\ Sure], label: "Is there plenty of parking?"%>
      </div>
      <div class="radio_buttons col-xs-4">
        <%= f.input :water, as: :radio_buttons, collection: %w[Yes No Not\ Sure], label: "Is there water nearby?"%>

      </div>
    </div>



    <div class="submit_"><%= f.submit 'Create', class: 'btn btn-primary' %></div>

    <br>

  <% end %>
</div>

app/views/places/show.html.erb
  <div class="frosty text-box col-xs-10 col-xs-offset-1">
    <h1><%= @place.name %></h1>
    <br>
    <strong>Address:</strong> <i><%= @place.address %></i>
    <br><br>
    <strong>Description:</strong> <%= @place.description %>
    <br>
    <br>
    <strong>Additional info:</strong>
    <br>
    Restroom: <%= @place.restroom %>
    <br>
    Parking: <%= @place.parking %>
    <br>
    Water: <%= @place.water %>
    <br>
    <br>




      <% if @place.latitude.present? && @place.longitude.present? %>

        <script>

          function initMap() {
            var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 12,
              center: myLatLng
            });

            var marker = new google.maps.Marker({
              position: myLatLng,
              map: map,
              title: 'Hello World!'
            });
          }
        </script>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-Qe8IvNlsFje1kkcZ9IapbeeAoAsNaIY&callback=initMap">
        </script>

        <div id="map"></div>

      <% end %>
      <br>
    <div class="pull-right">
      <% if current_user && current_user == @place.user %>
        <%= link_to 'Edit', edit_place_path(@place), class: "btn btn-primary" %>
        <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
      <% end %>

    </div>

  </div>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>


    <title>Hoop Spots</title>



  </head>
  <body id="court">





  <br />
  <div class="frosty col-xs-10 col-xs-offset-1 text-center style-box">
    <br />
    <h1>Welcome to Hoop Spots!</h1>
    <br />
    <br>
    <h4>This site is intended for basketball players who are looking for a place to play some pick up basketball.
    </h4>
    <h4>Feel free to add your own places to hoop.</h4>
    <br />
    <br><br>
    <%= link_to 'Find local spots near you', places_path, :class => 'btn btn-primary btn-lg' %>
    <br />
    <br />


  </div>








  </body>
</html>

app/views/static_pages/rules.html.erb
<br>
<h1 class=text-center>Basketball Pickup Game Etiquette</h1>
<br>
<div class="frosty col-xs-10 col-xs-offset-1  style-box">
  <br>
  <ul>

    <li>When you step on the court, find someone and ask who has next. If they do, ask them if you can "run" with them. If they size you up and reject your offer, you have two options now. Either punch them in the face or be really sad that you don't look athletic.</li>
    <br>
    <li>Always be alert of what is happening in the game while you are waiting to play. If you or your ball interfere with play, you will feel really bad.</li>
    <br>
    <li>You should only call a foul when someone has fouled you. Do not call a foul on a play regarding other people. If you want to see why this is important, go to a local LA fitness. There will be the stupid people arguing because everyone thinks they are a ref.</li>
    <br>
    <li>If someone sets a moving screen on you, make sure you get them back at some point, unless they have 25 pounds on you.</li>
    <br>
    <li>If you shoot an airball, look really confused and rub your hands. Make it appear as if it slipped or you had something on your hands.</li>
    <br>
    <li>If you were wide open for two plays in a row, but were not passed to, you have the right to walk slowly and not play defense.</li>
    <br>
    <li>If someone says "ball don't lie" and tells you to shoot for it, play the numbers game. None of you scrubs can shoot the 3-ball at 50%. Defer the option to him to shoot for it.</li>
    <br>
    <li>If you make a stupid play, scream "My bad!". It will get you off the hook (only the first time though).</li>
  </ul>
</div>